## this yaml file applies across the entire site

project:
  type: website

website:
  title: "hierarchy"
  site-url: https://www.
  description: "A great sample blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



